### ISSUE TITLE
Is there a way to customize the concealment?

### ISSUE THREAD

**Issue by dawsoneliasen** [vim-pandoc/vim-rmarkdown#30]
For example, disabling the replacement of # with the section symbol.

**Comment by BirgerNi** [comment]
Concealing is handled by the vim-pandoc-syntax plugin. The docs are pretty good. You can put `let g:pandoc#syntax#conceal#cchar_overrides = {'atx': '#'}` in your `.vimrc` to keep the `#` section symbol.

**Comment by dawsoneliasen** [comment]
@BirgerNi Thank you very much! This should help a lot :)
